
sensors:
   gps:
      serial_path: "/dev/ttyACM0"
      serial_speed: 57600
      min_sats: 4
   
core:
   flash_enabled: false

   logger:
      level: 3
      details: 2

   controllers:
      debug_host: "10.0.1.5"
      debug_port: 5555
      
      attitude:
         calibrate: false
         angle_max: 0.17
         p: 0.64
         i: 0.0
         i_max: 0.0
         d: 0.003
         pitch_bias: -0.022
         roll_bias: 0.03
 
      altitude:
         manual: false
         speed_p: 0.1
         speed_i: 0.4
         speed_imax: 100.0

      yaw:
         manual: false
         speed_min: 0.05
         speed_std: 0.1
         speed_max: 0.2
         speed_slope: 1.0
         speed_p: 0.24
         speed_i: 0.7
         speed_imax: 100.0

      navigation:
         speed_p: 0.4
         speed_min: 0.5
         speed_std: 2.0
         speed_max: 3.5
         sqrt_shift: 3.0
         sqrt_scale: 0.25
         square_shift: 0.5
         pos_i: 0.015
         pos_i_max: 5.0
         ortho_p: 0.0

   model:
      ultra_noise: 1.0e-2
      baro_noise: 1.0e-2
      gps_noise: 4.0e-3
      process_noise: 1.0e-6
      acc_avg_update_s: 60
      x_acc_avg: 0.0
      y_acc_avg: 0.0
      z_acc_avg: -9.81

   actuators:
      mk_fc:
         serial_port: "/dev/ttyUSB2"
         setting: 4

   sensors:
      
      rc_dsl:
         serial_port: "/dev/ttyUSB3"
      
      chr_6dm:
         serial_port: "/dev/ttyUSB0"
         device_conf_file: "config/chr-6dm.conf"
         process_covar: 1.0e-6
         mag_covar: 1.0e-3
         acc_covar: 1000.0
      
      voltage:
         sysfs_path: "/sys/class/hwmon/hwmon0/device/in7_input"

