
#
# SYSTEM SERVICES CONFIGURATION FILE
# ##################################
#
# purpose: definition of services by name and their project-relative executable paths
# 


aircomm_swarm:
  binary: 'missions/aircomm_swarm/aircomm_swarm.py'
  depends: [aircomm]

aircomm:
  binary: 'aircomm/aircomm_server.py'
  depends: [opcd]

icarus:
  binary: 'icarus/icarus.py'
  depends: [core, powerman]

gps_sensor:
  binary: 'sensors/gps_sensor/gps_sensor'

imms_sensor:
  binary: 'sensors/imms_sensor/imms_sensor'

powerman:
  binary: 'powerman/powerman.py'
  depends: [opcd]

core:
  binary: 'core/src/core'
  depends: [opcd, gps_sensor]

opcd:
  binary: 'opcd/opcd.py'
