
#
# SYSTEM SERVICES CONFIGURATION FILE
# ##################################
#
# purpose: definition of services by name and their project-relative executable paths
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

- name: arbiter
  binary: 'arbiter/src/arbiter.py'

- name: gps_sensor
  binary: 'sensors/gps/src/gps_sensor.py'

- name: core
  binary: 'core/src/core'
  args: '-f $MOBICOM_SUBPROJECT_PATH/components/core/config/core.conf'

