
#
# SYSTEM SERVICES CONFIGURATION FILE
# ##################################
#
# purpose: definition of services by name and their project-relative executable paths
# 


aircomm_swarm:
  binary: 'missions/aircomm_swarm/aircomm_swarm.py'
  depends: [aircomm]

aircomm:
  binary: 'aircomm/aircomm_server.py'
  depends: [opcd]

icarus:
  binary: 'icarus/icarus.py'
  depends: [core, powerman]

gps_sensor:
  binary: 'sensors/gps/gps_sensor'
  depends: [opcd]

imms_sensor:
  binary: 'sensors/imms/imms_sensor'

wifi_sensor:
  binary: 'sensors/wifi/wifi_sensor.py'

wifi_logger:
  binary: 'logging/wifi/wifi_logger.py'
  depends: [core, wifi_sensor]

powerman:
  binary: 'powerman/powerman.py'
  depends: [opcd]

core:
  binary: 'core/core'
  depends: [opcd, gps_sensor]

core_debug_writer:
  binary: 'logging/core_debug_writer/core_debug_writer.py'

opcd:
  binary: 'opcd/opcd.py'
