
#
# SYSTEM CONFIGURATION FILE
# #########################
#
# purpose: definition of intercomponent communication relations
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

components:

   - name: confserver
     gates:
      - ctrl: rep
      - update: pub

   - name: core
     gates:
      - update: sub

   - name: confshell
     gates:
      - ctrl: req
   
#
# component connections (component_a.gate_x -- component_b.gate_y)
#

connections:

#   - [ confserver.ctrl,     core.ctrl          ]
   - [ confserver.update,   core.update        ]
   - [ confshell.ctrl,      confserver.ctrl    ]
   
