
#
# SYSTEM CONFIGURATION FILE
# #########################
#
# purpose: definition of intercomponent communication relations
# 


#
# component definitions:
# - each component needs to define:
#    - its name
#    -  a list of gates
# - every gate consists of a name mapped to a type 
#   [pub, sub, req, rep]
#

components:

   - name: gps_sensor
     gates:
      - opcd_ctrl: req
      - gps: pub

   - name: gps_test
     gates:
      - gps: sub

   - name: gpx_logger
     gates:
      - gps: sub

   - name: core_logger
     gates:
      - log: sub

   - name: remote
     gates:
      - ctrl: req

   - name: ferry_ctrl
     gates:
      - hlsm: sub
      - ctrl: req
   
   - name: cmdshell
     gates:
      - ctrl: req
   
   - name: blackbox
     gates:
      - state_machine: sub
      - core_log: sub

   - name: icarus
     gates:
      - mon: sub
      - hlsm: pub
      - core: req
      - ctrl: rep

   - name: netscan
     gates:
      - networks: pub

   - name: localizer
     gates:
      - networks: sub
      - mon: sub
      - hlsm: sub
   
   - name: core
     gates:
      - log: pub
      - gps: sub
      - ctrl: rep
      - mon: pub
      - opcd_ctrl: req
      - opcd_event: sub
 
   - name: mavlink
     gates:
      - core_mon: sub
      - ctrl: req # opcd
      - gps: sub
      - icarus_ctrl: req
      - hlsm: sub

   - name: opcd
     gates:
      - ctrl: rep
      - event: pub

   - name: opcd_shell
     gates:
      - ctrl: req


#
# component connections (component_a.gate_x -- component_b.gate_y)
#

connections:

   - [ opcd.event,               core.opcd_event      ]
   - [ opcd.ctrl,                core.opcd_ctrl       ]
   - [ opcd.ctrl,                gps_sensor.opcd_ctrl ]
   - [ opcd.ctrl,                opcd_shell.ctrl      ]
   - [ localizer.mon,            core.mon             ]
   - [ mavlink.core_mon,         core.mon             ]
   - [ mavlink.ctrl,             opcd.ctrl            ]
   - [ mavlink.icarus_ctrl,      icarus.ctrl          ]
   - [ mavlink.hlsm,             icarus.hlsm         ]
   - [ remote.ctrl,              core.ctrl            ]
   - [ localizer.networks,       netscan.networks     ]
   - [ core_logger.log,          core.log             ]
   - [ gps_sensor.gps,           core.gps             ]
   - [ gps_sensor.gps,           mavlink.gps          ]
   - [ icarus.ctrl,             ferry_ctrl.ctrl      ]
   - [ ferry_ctrl.hlsm,          icarus.hlsm         ]
   - [ blackbox.state_machine,   icarus.hlsm         ]
   - [ blackbox.core_log,        core.log             ]
   - [ icarus.hlsm,             localizer.hlsm       ]
   - [ icarus.ctrl,             cmdshell.ctrl        ]
   - [ core.ctrl,                icarus.core         ]
   - [ core.mon,                 icarus.mon          ]
   - [ gpx_logger.gps,           gps_sensor.gps       ]
   - [ gps_sensor.gps,           gps_test.gps         ]
   
