#!/usr/bin/env python

import sys
import zmq
from gps_data_pb2 import GpsData
from zmq_ipc import generate_map


socket = generate_map('gps_test')['gps']
gps_data = GpsData()
print 'waiting for gps data'
try:
   while True:
      str = socket.recv()
      gps_data.ParseFromString(str)
      print gps_data
except:
   print 'terminated by user'

